### ISSUE TITLE
A scrolling problem occurs when the input field contains too much content

### ISSUE THREAD

**Issue by xavierchen2021** [e-roy/gemini-pro-vision-playground#15]
As shown in the figure, when a few lines of code are entered into the text box, the upper dialogue area is covered, and you cannot scroll to the top to see the previous answer

<img width="835" alt="image" src="https://github.com/e-roy/gemini-pro-vision-playground/assets/97932955/d88b9ab2-55a5-43bf-985d-12ff997c7a99">

**Comment by e-roy** [comment]
Thank you for spotting this.  Reopening
