### ISSUE TITLE
Error: HTTP error! status: 500

### ISSUE THREAD

**Issue by barreler126** [e-roy/gemini-pro-vision-playground#20]
Chat, got "Error: HTTP error! status: 500". No other response. Problem?

**Comment by barreler126** [comment]
Deployed on koyeb.com.

**Comment by e-roy** [comment]
I'm not familiar with koyeb.com, I've been mostly using  [https://vercel.com/](https://vercel.com/)

500 error sounds like you don't have the `GOOGLE_API_KEY` environment variable set in your deployment.  

Be sure to get your Google AI API key [here](https://ai.google.dev/tutorials/setup)

Please feel free to reopen if this is not the issue.
